obstacle_range: 3.0
raytrace_range: 3.0
max_obstacle_height: 2.0
min_obstacle_height: 0.10
footprint: [[0.305, 0.216], [0.305, -0.216], [-0.305, -0.216], [-0.305, 0.216]]
inflation_radius: 0.55
cost_scaling_factor: 10.0
transform_tolerance: 0.5
observation_sources: scan
scan:
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true

map_type: costmap
